
server:
  port: 8767
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/github-rep/SpringcloudConfig.git
          username: kxbk
          password: kclovezxl.1314.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

